version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    environment: 
      - PHPMYADMIN_PASSWORD=my_password
    ports:
      - '8082:8080'
      - '9443:8443'
    depends_on:
      - mariadb
  apache:
    image: 'docker.io/bitnami/apache:latest'
      ports:
        - '8080:8080'
        - '8443:8443'
      volumes:
        - /home/projects/dl/iomad/iomad:/app
volumes:
  mariadb_data:
    driver: local
